# Generated by Django 4.2.5 on 2023-09-30 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='статус рассылки')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='время рассылки')),
                ('day', models.DateField(default=datetime.datetime.today, verbose_name='Дата начала')),
                ('topic_mail', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('body_mail', models.CharField(max_length=100, verbose_name='Тело письма')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='Получатель/Получатели')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_send', models.DateTimeField(default=None, verbose_name='дата и время последней попытки')),
                ('status_send', models.CharField(max_length=150, verbose_name='Статус попытки')),
                ('last_attempt_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='Рассылка,которая отправлялась')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
