# Generated by Django 4.2.5 on 2023-10-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailingsettings_owner_mailingsettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_change_mailing_status', 'Can_change_mailing_status')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
    ]
