# Generated by Django 4.2.5 on 2023-10-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_change_mailing_status', 'Can change mailing status')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
    ]
